### PR TITLE
Issue #270 Added more supported Visual Studio versions

### PR DESCRIPTION
**Pull request by SzymonSel**

### CODE REVIEW

**Comment by rprouse** [comment]
I don't understand why this is needed. Is 3.6 not installing in VS 2013 Ultimate update 5 for you? It installs fine in Pro for me,

image

**Comment by pepekpl** [comment]
It failed for some reason.
Here is a log
2016-11-22 14:45:24 - Microsoft VSIX Installer
2016-11-22 14:45:24 - -------------------------------------------
2016-11-22 14:45:25 - Initializing Install...
2016-11-22 14:45:25 - Extension Details...
2016-11-22 14:45:25 -  Identifier      : NUnit.NUnit3TestAdapter
2016-11-22 14:45:25 -  Name            : NUnit 3 Test Adapter
2016-11-22 14:45:25 -  Author          : Terje Sandstrom
2016-11-22 14:45:25 -  Version         : 4.0.0.0
2016-11-22 14:45:25 -  Description     : NUnit 3 adapter for running tests in Visual Studio. Works with NUnit 3.x, use the NUnit 2 adapter for 2.x tests.
2016-11-22 14:45:25 -  Locale          : en-US
2016-11-22 14:45:25 -  MoreInfoURL     : https://github.com/nunit/docs/wiki/VS-Adapter
2016-11-22 14:45:25 -  InstalledByMSI  : False
2016-11-22 14:45:25 -  SupportedFrameworkVersionRange : [4.5,)
2016-11-22 14:45:25 - 
2016-11-22 14:45:25 -  Supported Products : 
2016-11-22 14:45:25 -   Microsoft.VisualStudio.Community
2016-11-22 14:45:25 -    Version : [11.0,16.0)
2016-11-22 14:45:25 - 
2016-11-22 14:45:25 -  References      : 
2016-11-22 14:45:25 - 
2016-11-22 14:45:25 - Searching for applicable products...
2016-11-22 14:45:27 - Found installed product - Microsoft Visual Studio Ultimate 2013
2016-11-22 14:45:27 - Found installed product - Microsoft Visual Studio Premium 2013
2016-11-22 14:45:27 - Found installed product - Microsoft Visual Studio Professional 2013
2016-11-22 14:45:27 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
2016-11-22 14:45:27 - Found installed product - Global Location
2016-11-22 14:45:27 - Found installed product - ssms
2016-11-22 14:45:27 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by rprouse** [comment]
That log is for 4.0 which isn't released. When you built it, did you build it with VS 2015 or 17? Do you get the same log errors with version 3.6 downloaded from the marketplace?

**Comment by pepekpl** [comment]
nunit screen
Please take a look

**Comment by SzymonSel** [comment]
I've built it on VS 2015 Enterprise. Add had no issues with the extention being dowloaded from the market place. Seems like this is an issue for older VS version. 

Perhaps the "Ultimate" edition doesn't fall in the "Community" category. I did have an impression that "Community" would catch those editions and any higher ones (Pro, Ultimate, Enterprise etc) - so that thae target edition Id is actualy the lowest appliable. 
But it looks like I'm either wrong or the 2013 Ultimate edition is an exception from this rule.

**Comment by rprouse** [comment]
Thanks for the changes. We are going to add the same to the NUnit 2 adapter.

**Comment by SzymonSel** [comment]
Glad I could contribute!

**Comment by OsirisTerje** [comment]
@rprouse has made the corresponding changes to the NUnit 2 adapter here: https://github.com/nunit/nunit-vs-adapter/commit/0b2ceb5587725be1a82acc76dd5b49f35a2d1ef1

**Pull request merged**
