### PR TITLE
Support netcoreapp 2.0 with nunit engine netstandard2.0

### PR DESCRIPTION
**Pull request by nvborisenko**
Added `netcoreapp2.0` target framework which will use nunit engine `standard 2.0`. This PR is in additional to PR #551

### CODE REVIEW

**Comment by OsirisTerje** [comment]
@nvborisenko Thanks for this PR!  
It seems to have a lot more changes than what you have done.  I am not able to figure out what to look at here.  It seems you have been working on an outdated fork.  Can you update your fork, and then try to push up again?  We need to get the number of changed files down to what matters.

**Comment by nvborisenko** [comment]
I updated branch from `origin/master` and all commits came from master. I can create another PR with outdated `netstardard-engine` branch with exact my changes. What do you prefer?

**Comment by nvborisenko** [comment]
Closing it, TestAdapter 3.13 supports netcoreapp2.0

**Comment by nvborisenko** [comment]
Will prepare another PR to master branch. Closing it due this is complicated for merging.

**Pull request closed without merging**
