### PR TITLE
Refactor TraitsFeature

### PR DESCRIPTION
**Pull request by jnm2**
When I came to implement the Explicit category for https://github.com/nunit/nunit3-vs-adapter/issues/47, I found TraitsFeature a bit daunting to wrap my head around.

The addition of tracking the Explicit category would introduce even more complexity, especially because I wanted to easily switch it between a trait, a category, and a brand new property. The cached representation `List<Trait>` was not very easy to tinker with, the way it was mapped back and forth to TestCases and from XmlNodes. So I did a spike.

This PR introduces `TestTraitInfo` as a way to isolate the logic of parsing, caching, combining, and applying of test properties from each other. I expect a performance increase due to several choices in the new implementation, but simplicity was the real goal.

So, for example, this would be the entire implementation of the new Explicit category: https://github.com/nunit/nunit3-vs-adapter/commit/0261bf65f633d777123f90b62d07749c9014f6a3

@OsirisTerje Hopefully the commit messages are good explanations. If this is too many changes, that's no problem. It's just an idea.

### CODE REVIEW

**Comment by jnm2** [comment]
@OsirisTerje What do you say—skip this for 3.10 and do the equivalent of https://github.com/nunit/nunit3-vs-adapter/commit/0261bf65f633d777123f90b62d07749c9014f6a3?

**Comment by OsirisTerje** [comment]
Yes, that would be awesome.  

About the refactoring, some of it looks good, some of it I don't understand, and some are in between :-)  Let's talk a bit about it before we go further, but please get  0261bf6  in !

**Comment by jnm2** [comment]
Alright, I'm on it!

**Comment by jnm2** [comment]
Now it'll take a bit of cleverness for me to get 0261bf6 in without this PR and it won't be nearly as clear, but I'm on it!

**Comment by jnm2** [comment]
Wait a minute... that was a lot easier than I though it was going to be 😄

**Comment by jnm2** [comment]
Haha, I don't know why I thought it was complicated before... 😄 PR is up already! https://github.com/nunit/nunit3-vs-adapter/pull/467

**Comment by jnm2** [comment]
This got stale and may be superseded by @OsirisTerje's plans.

**Pull request closed without merging**
