### PR TITLE
Added circuit breaker to prevent performance problem

### LINKED ISSUE #460: Failure to load dependency assembly causes hang
Using the 3.10 dev VSIX (2f4079dadd77ecdadb6d069d7e80df6be7ed7005, https://ci.appveyor.com/project/CharliePoole/nunit3-vs-adapter/build/3.10.0-dev-00750/artifacts).

There's one project where in the process of locating navigation info, we call `GetCustomAttributes(testMethod)` which causes our navigation provider's reflection-only appdomain to try to load nunit.framework.dll and fail to locate it.

I had added some fail-safety and it will continue on and succeed, but it's so slow. In this one project, it calls `GetCustomAttributes` on so many test methods (each of which causes the nunit.framework.dll load failure) that it appears to hang for an unacceptably long time.

I don't yet know why it fails to find nunit.framework.dll, but before we fix that, I want to add another circuit breaker. I wonder what the best approach is—disable calls to `GetStateMachineType` for the current test assembly after the first exception, and same for `GetDeclaringType`?

<details>
<summary>Stack trace</summary>

```
 	[Managed to Native Transition]	
>	mscorlib.dll!System.ModuleHandle.ResolveMethodHandleInternalCore(System.Reflection.RuntimeModule module, int methodToken, System.IntPtr[] typeInstantiationContext, int typeInstCount, System.IntPtr[] methodInstantiationContext, int methodInstCount)	Unknown
 	mscorlib.dll!System.ModuleHandle.ResolveMethodHandleInternal(System.Reflection.RuntimeModule module, int methodToken, System.RuntimeTypeHandle[] typeInstantiationContext, System.RuntimeTypeHandle[] methodInstantiationContext)	Unknown
 	mscorlib.dll!System.Reflection.CustomAttributeData.CustomAttributeData(System.Reflection.RuntimeModule scope, System.Reflection.CustomAttributeRecord caRecord)	Unknown
 	mscorlib.dll!System.Reflection.CustomAttributeData.GetCustomAttributes(System.Reflection.RuntimeModule module, int tkTarget)	Unknown
 	mscorlib.dll!System.Reflection.CustomAttributeData.GetCustomAttributesInternal(System.Reflection.RuntimeMethodInfo target)	Unknown
 	mscorlib.dll!System.Reflection.RuntimeMethodInfo.GetCustomAttributesData()	Unknown
 	mscorlib.dll!System.Reflection.CustomAttributeData.GetCustomAttributes(System.Reflection.MemberInfo target)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.Metadata.DirectReflectionMetadataProvider.GetStateMachineType(string assemblyPath, string reflectedTypeName, string methodName)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.Metadata.ReflectionAppDomainMetadataProvider.AppDomainHelper.GetStateMachineType(string assemblyPath, string reflectedTypeName, string methodName)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage msg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage reqMsg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Lifetime.LeaseSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage msg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage reqMsg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessageCallback(object[] args)	Unknown
 	mscorlib.dll!System.Threading.Thread.CompleteCrossContextCallback(System.Threading.InternalCrossContextDelegate ftnToCall, object[] args)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage reqMsg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage(System.Runtime.Remoting.Messaging.IMessage msg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(byte[] reqStmBuff, System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage smuggledMcm, out System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage smuggledMrm)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback(object[] args)	Unknown
 	mscorlib.dll!System.Threading.Thread.CompleteCrossContextCallback(System.Threading.InternalCrossContextDelegate ftnToCall, object[] args)	Unknown
 	[AppDomain (testhost.x86.exe, #1) -> AppDomain (NUnit.VisualStudio.TestAdapter.Metadata.ReflectionAppDomainMetadataProvider, #9)]	
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatch(byte[] reqStmBuff, System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage smuggledMcm, out System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage smuggledMrm)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage reqMsg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Proxies.RemotingProxy.CallProcessMessage(System.Runtime.Remoting.Messaging.IMessageSink ms, System.Runtime.Remoting.Messaging.IMessage reqMsg, System.Runtime.Remoting.Contexts.ArrayWithSize proxySinks, System.Threading.Thread currentThread, System.Runtime.Remoting.Contexts.Context currentContext, bool bSkippingContextChain)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Proxies.RemotingProxy.InternalInvoke(System.Runtime.Remoting.Messaging.IMethodCallMessage reqMcmMsg, bool useDispatchMessage, int callType)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Proxies.RemotingProxy.Invoke(System.Runtime.Remoting.Messaging.IMessage reqMsg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(ref System.Runtime.Remoting.Proxies.MessageData msgData, int type)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.Metadata.ReflectionAppDomainMetadataProvider.GetStateMachineType(string assemblyPath, string reflectedTypeName, string methodName)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.NavigationDataProvider.DoSafe(System.Func<string, string, string, NUnit.VisualStudio.TestAdapter.Metadata.TypeInfo?> method, string assemblyPath, string declaringTypeName, string methodName)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.NavigationDataProvider.GetNavigationData(string className, string methodName)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestCaseFromXmlNode(System.Xml.XmlNode testNode)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.TestConverter.ConvertTestCase(System.Xml.XmlNode testNode)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(string assemblyPath, NUnit.Engine.TestFilter filter)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(System.Collections.Generic.IEnumerable<string> sources, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle)	Unknown
 	Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.Utilities.LazyExtension<Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ITestExecutor, Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ITestExecutorCapabilities> executor, System.Tuple<System.Uri, string> executorUriExtensionTuple, Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Adapter.RunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle)	Unknown
 	Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors.AnonymousMethod__0()	Unknown
 	Microsoft.TestPlatform.PlatformAbstractions.dll!Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	Unknown
```

</details>  

 I'll prioritize this above everything else.

/cc @OsirisTerje for implementation questions above and for 3.10 planning.

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #460.

Tested against the problem project. This PR resolves the performance issue. In a separate PR, I'll figure out why the reflection appdomain is failing to load nunit.framework.dll for the problem project.

### CODE REVIEW

**Comment by CharliePoole** [comment]
Since @OsirisTerje has not published rules for merging in the adapter projects, I've been going on the assumption that he has to approve everything. That would seem to be logical anyway, since he is the lead and @rprouse is the only other member of that Extension team.

Those of us who are core team members have write access to every project, but I thought that was only so we could jump in if the project lead left, not for everyday usage. That's how I've been acting, anyway.

**Comment by jnm2** [comment]
Ah, got it.

**Comment by OsirisTerje** [comment]
I would appreciate if you leave the approval to me, unless something is very critical to fix and I am absent.  I do keep notes for the PRs and the issues that we solve, so it is easier if I do it this way.  Please feel free to ping me on Glitter/Skype whatever if I am delaying something. 

I also really appreciate the reviews being done.

**Comment by jnm2** [comment]
That's good to know! Thanks!

**Pull request merged**
