### PR TITLE
Release 3.7

### PR DESCRIPTION
**Pull request by CharliePoole**
**Do Not Merge**

This branch will be used for the release and then merged manually.

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
Just a note if you're re-updating icons Charlie - the NuGet package here uses a 90x90, everywhere else uses:

    https://cdn.rawgit.com/nunit/resources/master/images/icon/nunit_256.png

All the other repos should be standardised already. 😄

**Comment by CharliePoole** [comment]
Ah! I noticed that but assumed that was the right size. I'll change the url.

**Comment by rprouse** [comment]
Looks good to me.

**Comment by CharliePoole** [comment]
@rprouse @OsirisTerje Can one of you download the latest build artifacts from AppVeyor and try to use them? https://ci.appveyor.com/project/CharliePoole/nunit3-vs-adapter/build/3.7.0-ci-00394-pr-299/artifacts

I am unable to install either the Appveyor-built vsix or my local build on VS2017. However, I'm suspecting my installation, so I'd like somebody else to try it.

**Comment by OsirisTerje** [comment]
Just checked the vsix, works like  a charm :-)

**Comment by CharliePoole** [comment]
@OsirisTerje Thanks! In that case I'll proceed with the release. Whatever is wrong with my setup can be dealt with another time. As of now, I can only install the vsix in VS2015, not VS2017.

**Pull request merged**
