### PR TITLE
Fixed missing navigation data when adapter and test assemblies are in separate folders

### LINKED ISSUE #460: Failure to load dependency assembly causes hang
Using the 3.10 dev VSIX (2f4079dadd77ecdadb6d069d7e80df6be7ed7005, https://ci.appveyor.com/project/CharliePoole/nunit3-vs-adapter/build/3.10.0-dev-00750/artifacts).

There's one project where in the process of locating navigation info, we call `GetCustomAttributes(testMethod)` which causes our navigation provider's reflection-only appdomain to try to load nunit.framework.dll and fail to locate it.

I had added some fail-safety and it will continue on and succeed, but it's so slow. In this one project, it calls `GetCustomAttributes` on so many test methods (each of which causes the nunit.framework.dll load failure) that it appears to hang for an unacceptably long time.

I don't yet know why it fails to find nunit.framework.dll, but before we fix that, I want to add another circuit breaker. I wonder what the best approach is—disable calls to `GetStateMachineType` for the current test assembly after the first exception, and same for `GetDeclaringType`?

<details>
<summary>Stack trace</summary>

```
 	[Managed to Native Transition]	
>	mscorlib.dll!System.ModuleHandle.ResolveMethodHandleInternalCore(System.Reflection.RuntimeModule module, int methodToken, System.IntPtr[] typeInstantiationContext, int typeInstCount, System.IntPtr[] methodInstantiationContext, int methodInstCount)	Unknown
 	mscorlib.dll!System.ModuleHandle.ResolveMethodHandleInternal(System.Reflection.RuntimeModule module, int methodToken, System.RuntimeTypeHandle[] typeInstantiationContext, System.RuntimeTypeHandle[] methodInstantiationContext)	Unknown
 	mscorlib.dll!System.Reflection.CustomAttributeData.CustomAttributeData(System.Reflection.RuntimeModule scope, System.Reflection.CustomAttributeRecord caRecord)	Unknown
 	mscorlib.dll!System.Reflection.CustomAttributeData.GetCustomAttributes(System.Reflection.RuntimeModule module, int tkTarget)	Unknown
 	mscorlib.dll!System.Reflection.CustomAttributeData.GetCustomAttributesInternal(System.Reflection.RuntimeMethodInfo target)	Unknown
 	mscorlib.dll!System.Reflection.RuntimeMethodInfo.GetCustomAttributesData()	Unknown
 	mscorlib.dll!System.Reflection.CustomAttributeData.GetCustomAttributes(System.Reflection.MemberInfo target)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.Metadata.DirectReflectionMetadataProvider.GetStateMachineType(string assemblyPath, string reflectedTypeName, string methodName)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.Metadata.ReflectionAppDomainMetadataProvider.AppDomainHelper.GetStateMachineType(string assemblyPath, string reflectedTypeName, string methodName)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage msg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage reqMsg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Lifetime.LeaseSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage msg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage reqMsg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessageCallback(object[] args)	Unknown
 	mscorlib.dll!System.Threading.Thread.CompleteCrossContextCallback(System.Threading.InternalCrossContextDelegate ftnToCall, object[] args)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage reqMsg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage(System.Runtime.Remoting.Messaging.IMessage msg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(byte[] reqStmBuff, System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage smuggledMcm, out System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage smuggledMrm)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback(object[] args)	Unknown
 	mscorlib.dll!System.Threading.Thread.CompleteCrossContextCallback(System.Threading.InternalCrossContextDelegate ftnToCall, object[] args)	Unknown
 	[AppDomain (testhost.x86.exe, #1) -> AppDomain (NUnit.VisualStudio.TestAdapter.Metadata.ReflectionAppDomainMetadataProvider, #9)]	
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatch(byte[] reqStmBuff, System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage smuggledMcm, out System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage smuggledMrm)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage reqMsg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Proxies.RemotingProxy.CallProcessMessage(System.Runtime.Remoting.Messaging.IMessageSink ms, System.Runtime.Remoting.Messaging.IMessage reqMsg, System.Runtime.Remoting.Contexts.ArrayWithSize proxySinks, System.Threading.Thread currentThread, System.Runtime.Remoting.Contexts.Context currentContext, bool bSkippingContextChain)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Proxies.RemotingProxy.InternalInvoke(System.Runtime.Remoting.Messaging.IMethodCallMessage reqMcmMsg, bool useDispatchMessage, int callType)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Proxies.RemotingProxy.Invoke(System.Runtime.Remoting.Messaging.IMessage reqMsg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(ref System.Runtime.Remoting.Proxies.MessageData msgData, int type)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.Metadata.ReflectionAppDomainMetadataProvider.GetStateMachineType(string assemblyPath, string reflectedTypeName, string methodName)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.NavigationDataProvider.DoSafe(System.Func<string, string, string, NUnit.VisualStudio.TestAdapter.Metadata.TypeInfo?> method, string assemblyPath, string declaringTypeName, string methodName)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.NavigationDataProvider.GetNavigationData(string className, string methodName)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestCaseFromXmlNode(System.Xml.XmlNode testNode)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.TestConverter.ConvertTestCase(System.Xml.XmlNode testNode)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(string assemblyPath, NUnit.Engine.TestFilter filter)	Unknown
 	NUnit3.TestAdapter.dll!NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(System.Collections.Generic.IEnumerable<string> sources, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle)	Unknown
 	Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.Utilities.LazyExtension<Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ITestExecutor, Microsoft.VisualStudio.TestPlatform.Common.Interfaces.ITestExecutorCapabilities> executor, System.Tuple<System.Uri, string> executorUriExtensionTuple, Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Adapter.RunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle)	Unknown
 	Microsoft.TestPlatform.CrossPlatEngine.dll!Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors.AnonymousMethod__0()	Unknown
 	Microsoft.TestPlatform.PlatformAbstractions.dll!Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	Unknown
```

</details>  

 I'll prioritize this above everything else.

/cc @OsirisTerje for implementation questions above and for 3.10 planning.

### PR DESCRIPTION
**Pull request by jnm2**
Entirely resolves #460! 🎉

Simple root cause: I had set up the reflection-only AppDomain with the ApplicationBase set to the directory containing the adapter rather than the directory containing the test assembly and its dependencies. This, its dependencies failed to load in that AppDomain and the navigation data went missing due to FileNotFoundException.

The hard part was figuring out a way to set up a test that would fail. The simplest approach I was able to find over the last two days was to add Roslyn and compile tiny assemblies to a temp folder. This had a minor complication, noted in NavigationDataProviderTests.

### CODE REVIEW

**Comment by jnm2** [comment]
Missed this at first on my machine. The reflection-only AppDomain is locking the temporary assemblies and preventing the test from cleaning them up. 😒 Setting AppDomainSettings.ShadowCopy = "true" hasn't worked so far. Not sure what the best approach is yet.

**Comment by jnm2** [comment]
Missed this, but the test is failing to clean up the temp files because DiaSession loads the assembly into the current AppDomain which leaves the file locked. I'll have to come up with another way to test this since DiaSession really has nothing to do with this PR.

**Comment by jnm2** [comment]
Added a commit. Ready for review!

**Comment by jnm2** [comment]
Tried this in the large project and found one more bit of setup I need to do that I didn't do yet: loading the test assembly's .config file. Otherwise ordinary binding redirects generated by projects using NuGet packages will occasionally cause FileNotFoundException and stop helping DiaSession with navigation data.

Even though this is a one-liner, I need to write a test for this first. 😁

**Comment by jnm2** [comment]
Turns out you can't use ReflectionOnlyLoad if you need binding redirects to work.
On the bright side, we have some super-robust testing to make sure we stay this way!

Everything seems to be working!

**Comment by jnm2** [comment]
@OsirisTerje I've run this VSIX against the big project and everything is humming along beautifully. Seems ideal.

**Comment by OsirisTerje** [comment]
Cool!  I'll have a look asap.  After merge I would like to do some runs myself on some of my projects.  Anyone else wanting to test then would be appreciated.  I'll post up the package link here afterwards

**Pull request merged**
