### PR TITLE
Fix acceptance tests for 15.9

### PR DESCRIPTION
**Pull request by jnm2**
Quick fix to get acceptance tests working on master.

### CODE REVIEW

**Comment by jnm2** [comment]
Hold on. Microsoft.NET.Test.Sdk already has a .props that sets the IsTestProject property.

**Comment by jnm2** [comment]
Manually testing. This only affects netcoreapp1.0 targets. netcoreapp1.1- and netcoreapp2.0-targeted projects are fine without IsTestProject.

**Comment by jnm2** [comment]
Get this: `<TargetFrameworks>netcoreapp1.0</TargetFrameworks>` is fine, but `<TargetFrameworks>net40;netcoreapp1.0</TargetFrameworks>` starts failing just for the netcoreapp1.0 target unless you add IsTestProject or move to netcoreapp1.1.

**Comment by jnm2** [comment]
Also, if I remove `
    <add key="globalPackagesFolder" value="Isolated package cache" />` from `tests/nuget.config`, it starts working.

**Comment by jnm2** [comment]
Also, if I remove `<add key="globalPackagesFolder" value="Isolated package cache" />` from `tests/nuget.config`, it starts working.

Something is weirdly dependent on where the NuGet package cache is.

**Comment by jnm2** [comment]
Oh, `net40` is what's broken.

**Comment by jnm2** [comment]
This is the problem: https://github.com/dotnet/sdk/issues/2690

The workaround for our acceptance test projects can be to just target net45 instead.

**Comment by OsirisTerje** [comment]
yep, do that!  This is just our tests.

**Pull request merged**
