### PR TITLE
Changed name of adapter dll to end with the patterns *.TestAdapter.dll, ...

### PR DESCRIPTION
**Pull request by OsirisTerje**
...required for VS to locate it.  #13

### CODE REVIEW

**Comment by CharliePoole** [comment]
It looks like you missed some ProjectTests. You probably have a copy of the old dll name in your bin directory that is allowing them to pass.

How about adding a ProjectTest that verifies the name of the dll ends with ".TestAdapter.dll"?

**Comment by OsirisTerje** [comment]
Nice!  Will do!

**Comment by OsirisTerje** [comment]
Any other comments, - can this be merged now ?

**Comment by CharliePoole** [comment]
I usually delete the branch when I merge, but I wasn't sure how you have been doing it.

**Comment by OsirisTerje** [comment]
I usually don’t delete it – I kind of like to see the real history, - and it don’t bother me either.
And it is a good way to show other [new] people how we do it.  That is :  Branch – Pull Request – Comments – Merge.

But, as usual – I don’t mind either if it is deleted ☺


/Terje

**Pull request merged**
