### PR TITLE
Exclude the partition filter from test expansion

### PR DESCRIPTION
**Pull request by chris-smith-zocdoc**
Addressing my comment here https://github.com/nunit/nunit3-vs-adapter/issues/1138#issuecomment-2116067823

I saw the category filter doing this already and copied its approach. Please let me know if there is another approach you think I should take

### CODE REVIEW

**Comment by chris-smith-zocdoc** [comment]
@dotnet-policy-service agree company="Zocdoc"

**Comment by OsirisTerje** [comment]
@chris-smith-zocdoc Can you update?

**Comment by chris-smith-zocdoc** [comment]
@OsirisTerje I rebased, is there anything else I should do? 

If this approach is good with you I can also add tests, just need some guidance on where they should go and how to run them (I'm on Mac and am unfamiliar with Cake)

**Comment by OsirisTerje** [comment]
@chris-smith-zocdoc Thanks!

Building with cake is straightforward.  I am not familiar with Mac command line, but if you can run either the build.cmd file or the build.ps1 (powershell), or you can create a similar one for Mac, 

To build:  `build`
To test:  `build -t test`
To acceptance tests: `build -t acceptance`

The acceptance tests uses code for the test project and test class embedded in the test.  It then starts up the test system, 
includes the adapter package and run it.

**Comment by OsirisTerje** [comment]
@chris-smith-zocdoc I'll merge this now, in order to get it into version 4.6.

Would be nice if you managed to get some tests around it though, but it can in a separate PR.

**Pull request merged**
