### PR TITLE
Replaced Mono.Cecil

### LINKED ISSUE #296: Mono.Cecil causes OutOfMemoryException with new .csproj PDBs
I converted the old-style test .csproj targeting .NET Framework 4.6.2 to a new-style .csproj targeting the exact same .NET Framework 4.6.2 (VS2017 build 15.0.26020.0):

```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <RuntimeIdentifier>win</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.6.0" />
  </ItemGroup>
</Project>
```

All tests run exactly the same as they always have using the NUnit console runner, but no tests are discovered using the NUnit VS adapter. I found out why- Mono.Cecil is causing OutOfMemoryExceptions while reading the PDB to find source code locations:

```
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.CacheTypes(String assemblyPath)
   at NUnit.VisualStudio.TestAdapter.NavigationDataProvider.GetNavigationData(String className, String methodName)
   at NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestCaseFromXmlNode(XmlNode testNode)
   at NUnit.VisualStudio.TestAdapter.TestConverter.ConvertTestCase(XmlNode testNode)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer.ProcessTestCases(XmlNode topNode, ITestCaseDiscoverySink discoverySink, TestConverter testConverter
```

I want to stress that **this is not related to .NET Core**. The new PDB format will be used in the future for all normal .NET projects including .NET Framework projects.

The relevant Mono.Cecil PDB issue is at https://github.com/jbevain/cecil/issues/282.
Support for this new PDB format is shipped so far only in [0.10-beta1](https://github.com/jbevain/cecil/releases/tag/0.10-beta1) and [0.10-beta2](https://github.com/jbevain/cecil/releases/tag/0.10-beta2).

All we need is the source file and line number. I read through https://github.com/nunit/nunit3-vs-adapter/issues/183, but I'm concerned that Mono.Cecil might not be the best way to go. It's never going to be as reliable as, say, Roslyn. [xUnit's desktop VS test adapter](https://github.com/xunit/visualstudio.xunit/blob/master/xunit.runner.visualstudio.desktop/xunit.runner.visualstudio.desktop.csproj) also does not use Mono.Cecil.

Can we use Visual Studio to give us the source file and line number for a given assembly and type or member? That's going to be the most reliable since it's the IDE itself that will be doing the navigating.
If not, can we use Roslyn?

How close can we get to where this is all happening, so that ideally we don't end up chasing a moving target? It's [comments like this](https://github.com/nunit/nunit3-vs-adapter/blob/master/src/NUnitTestAdapter/NavigationDataProvider.cs#L56-L60) that make me worry that we're reinventing the wheel somewhere:

```c#
// Through NUnit 3.2.1, the class name provided by NUnit is
// the reflected class - that is, the class of the fixture
// that is being run. To use for location data, we actually
// need the class where the method is defined.
// TODO: Once NUnit is changed, try to simplify this.
```

Wouldn't it be better to hand Visual Studio an assembly path, a class name and a method and have Visual Studio or at least Roslyn do the work of figuring out what file and line number the method is defined in? I mean imagine when they add the Source Generators proposal. I'd rather offload this to VS and Roslyn since they are ultimately responsible to know all this stuff.
Otherwise we'll always be playing catch-up with new language and debugging features and crash, like we're doing right now?

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #296! 🎉

Everything is finished and just waiting on the merge of PRs https://github.com/nunit/nunit3-vs-adapter/pull/450 and https://github.com/nunit/nunit3-vs-adapter/pull/453!

NB: Rather than looking at the branch diff, please review each commit below the ——TEST MERGE—— lines individually. There are 12  commits, some large, so it'll probably make the most sense that way anyway. I will rebase onto master once the dependency PRs are in master.

### CODE REVIEW

**Comment by OsirisTerje** [comment]
The reason for moving to Mono.cecil is here: nunit/nunit3-vs-adapter #183 
Also found this issue nunit/nunit3-vs-adapter #138
And this should be checked out: nunit/nunit3-vs-adapter #163
And we still have this open on the NUNit2 adapter, https://github.com/nunit/nunit-vs-adapter/issues/6 
And see this comment in nunit/nunit3-vs-adapter #171 : "Now for the solution, I found that Microsoft.VisualStudio.TestPlatform.ObjectModel.DiaSession.GetNavigationData was unable to retrieve navigation data if the provided method was defined in a base class of the given class( rather than being defined in the given class itself). It's probably a limitation in DiaSession.GetNavigationData behaviour, but we can make up for that by looking up the real class containing the method definition and providing its name to DiaSession.GetNavigationData."

@jnm2 I locally merged the two other PRs, and I'm now looking at the branch jnm/replace_Cecil. I now see that the tests are no longer showing up in Visual Studio. We had the adapter as a package included, but I can't see it anymore. It's deletion might have slipped in my review of the changes.

**Comment by jnm2** [comment]
@OsirisTerje 

> I now see that the tests are no longer showing up in Visual Studio. We had the adapter as a package included, but I can't see it anymore. It's deletion might have slipped in my review of the changes.

This is because you have the 3.9 VSIX installed and it overrides any adapter-as-package in all projects. This is the last time you'll have to do this, but you'll need to disable the 3.9 VSIX in order to test this locally.

I deleted the the NUnit3TestAdapter 3.9 NuGet package reference for two reasons:

- Visual Studio was not even restoring the packages. It had a warning icon. Maybe because it conflicted with the adapter project reference? In any case, removing the NUnit3TestAdapter package reference made no difference to the discovery of tests either before or after this PR. They were still discovered in the Visual Studio Test Explorer window without the NuGet reference and with the VSIX disabled.

- Even if the NUnit3TestAdapter package reference worked, it would have prevented this PR from ever passing all tests because it's version 3.9, and version 3.9 has the Mono.Cecil issue.

I'll do the merge and comment on the issues.

**Comment by jnm2** [comment]
> The reason for moving to Mono.cecil is here: nunit/nunit3-vs-adapter #183

> There are various complications with use of DiaSession to retrieve navigation data in the adapter. One of the greatest is that we cannot easily use the console to run our navigation data tests.

This was mainly what https://github.com/nunit/nunit3-vs-adapter/pull/450 was about. A central point is that using self-executing tests isn't really what we want to test. The same point applies to running using NUnit Console.

On the practical side, you can use `build.ps1` to run navigation tests from the command line in addition to being able to run navigation tests from the Test Explorer.

**Comment by jnm2** [comment]
> And this should be checked out: nunit/nunit3-vs-adapter #163

I didn't remove any tests, so I preserved this behavior.

Tests: https://github.com/nunit/nunit3-vs-adapter/blob/446f36aa77270c59ce6998cb05c7df7b57dafd03/src/NUnitTestAdapterTests/NavigationDataTests.cs#L50-L51

Implementation:
https://github.com/nunit/nunit3-vs-adapter/blob/446f36aa77270c59ce6998cb05c7df7b57dafd03/src/NUnitTestAdapter/NavigationDataProvider.cs#L60-L66

**Comment by jnm2** [comment]
> And this should be checked out: nunit/nunit3-vs-adapter #163
> And see this comment in nunit/nunit3-vs-adapter #171 : "Now for the solution, I found that Microsoft.VisualStudio.TestPlatform.ObjectModel.DiaSession.GetNavigationData was unable to retrieve navigation data if the provided method was defined in a base class of the given class( rather than being defined in the given class itself). It's probably a limitation in DiaSession.GetNavigationData behaviour, but we can make up for that by looking up the real class containing the method definition and providing its name to DiaSession.GetNavigationData."

I didn't remove any tests, so I preserved this behavior.

Tests: https://github.com/nunit/nunit3-vs-adapter/blob/446f36aa77270c59ce6998cb05c7df7b57dafd03/src/NUnitTestAdapterTests/NavigationDataTests.cs#L50-L51

Implementation:
https://github.com/nunit/nunit3-vs-adapter/blob/446f36aa77270c59ce6998cb05c7df7b57dafd03/src/NUnitTestAdapter/NavigationDataProvider.cs#L60-L66

Also, this behavior was preserved: https://github.com/nunit/nunit3-vs-adapter/pull/315 (Support base-class tests from external assemblies):

https://github.com/nunit/nunit3-vs-adapter/blob/446f36aa77270c59ce6998cb05c7df7b57dafd03/src/NUnitTestAdapterTests/NavigationDataTests.cs#L57-L62

**Comment by jnm2** [comment]
@OsirisTerje I really appreciate your thoroughness here. 

> And we still have this open on the NUNit2 adapter, nunit/nunit-vs-adapter#6

I haven't seen this issue yet. Let me add tests and see what can be done.

**Comment by jnm2** [comment]
Looks like I was wrong about the Test Explorer working. The tests are discovered, but running and debugging don't do anything. I'll come back and correct this.

**Comment by jnm2** [comment]
Oh, duh. They are working. Just need to remember the instructions I added to the readme:

> To run and debug tests on .NET Framework, load `DisableAppDomain.runsettings`.

https://github.com/nunit/nunit3-vs-adapter/blob/master/README.md#developing

**Comment by jnm2** [comment]
I just had to remind myself of the instructions I added to the readme:

> To run and debug tests on .NET Framework, load `DisableAppDomain.runsettings`.

https://github.com/nunit/nunit3-vs-adapter/blob/master/README.md#developing

**Comment by jnm2** [comment]
@OsirisTerje Indeed, nunit/nunit-vs-adapter#6 is something to fix.

**Comment by jnm2** [comment]
@OsirisTerje Added two commits testing and fixing nunit/nunit-vs-adapter#6.

There are no outstanding issues that I know of, so, back to you. 😊

**Comment by Dispersia** [comment]
Hey! Not being pushy, glad to see this fixed, but any idea when this'll be pushed to nuget? If this fixes the mono cecil throw then it would be great to use :)

 Went back to test #371  and got the same issue @jons-aura got

**Comment by jnm2** [comment]
I'll let @OsirisTerje answer that, but in the meantime you can merge this with your nuget.config:

```xml
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="NUnit 3 VS adapter prerelease" value="https://ci.appveyor.com/nuget/nunit3-vs-adapter" />
    </packageSources>
</configuration>
```

**Comment by OsirisTerje** [comment]
We'll try to get it out real soon now, hopefully during the upcoming weekend, but we would also really appreciate some testing up front.  So if you (@Dispersia ) could add the link @jnm2 shows above and take it for a run, see if all works as it should, we would be grateful.  There are some changes here, and it needs some test runs.

**Comment by Dispersia** [comment]
Confirmed, works perfectly for me, thanks for the fixes guys :)

**Comment by jnm2** [comment]
I messed up the link there for the nuget.config (fixed).

**Pull request merged**
