### PR TITLE
Initial Cake build script

### PR DESCRIPTION
**Pull request by CharliePoole**
**Do Not Merge**

Ongoing experiments using Cake to build the adapter.

### CODE REVIEW

**Comment by rprouse** [comment]
@CharliePoole are you still working on this, or would you like one of us to take it up, or should it be dropped?

**Comment by CharliePoole** [comment]
This relates to #2

**Comment by CharliePoole** [comment]
@rprouse I was planning to get back to this at which point I would decide whether to drop it and start over. It's not a high priority for 3.0 AFAIC, but if you have bandwidth and want to do it that's OK with me.

**Comment by CharliePoole** [comment]
I'm dropping this in favor of an approach that doesn't use Cake or even an appveyor.yml script.

**Pull request closed without merging**
