### PR TITLE
Add LICENSE.txt via license element

### LINKED ISSUE #580: Fix licenseUrl in nuspec, will be deprecated
image

### PR DESCRIPTION
**Pull request by mikkelbu**
Fixes #580

### CODE REVIEW

**Comment by OsirisTerje** [comment]
@mikkelbu   Fungerer   build -t package ?

**Comment by mikkelbu** [comment]
> @mikkelbu Fungerer build -t package ?

Så vidt jeg har kunnet teste lokalt, så virker package target, og LICENSE.txt er nævnt i metadata. Det ligner også, at det har fungeret på appveyor, https://ci.appveyor.com/project/CharliePoole/nunit3-vs-adapter/builds/26600339#L1809

**Comment by OsirisTerje** [comment]
Yes, tried locally, it worked :-)  

Another thing - wonder why the Azure Pipeline builds have stopped running ?

**Comment by mikkelbu** [comment]
> Another thing - wonder why the Azure Pipeline builds have stopped running ? That is, for the pull requests. They work on master

I created https://github.com/nunit/nunit/issues/3338 one week ago and just spent 1 hour without any progress, but I'll examine it some more tonight. 

In the NUnit project master was passing jul 28
https://nunit.visualstudio.com/NUnit/_build/results?buildId=1892
but when I triggered a rebuild it failed on aug 3
https://nunit.visualstudio.com/NUnit/_build/results?buildId=1905
and examine the logs it seems that the image has been updated (git-lfs was bumped from 2.7.2 to 2.8.0 and the full change log is here https://github.com/microsoft/azure-pipelines-image-generation/commit/fcd0f07bc07b82d1fb649914917e67ac201eb5b2 - I guess).

**Pull request merged**
