### PR TITLE
Only un-escape unicode character encoding color codes Fix #1124

### LINKED ISSUE #1124: Mangled test output regression after problematic fix
Present in NUnit3TestAdapter 4.3.0 and newer.

## Description

When printing full file paths for a collection of DLLs on Windows, I found that after the string `\u` has been printed to the test output, subsequent test output would be mangled.

Minimal test case:
```csharp
TestContext.Out.WriteLine("UMMM {0}", "b\\3597805");
TestContext.Out.WriteLine("C:\\Windows\\System32\\user32.dll");
TestContext.Out.WriteLine("UMMM {0}", "b\\3597805");
```

Resulting output:
```
UMMM b\3597805
C:\Windows\System32\user32.dll
UMMM b奸05
```

Expected output:
```
UMMM b\3597805
C:\Windows\System32\user32.dll
UMMM b\3597805
```

## Cause

I've found that it's likely caused by this commit: https://github.com/nunit/nunit3-vs-adapter/commit/6a6e422a7b4874a2340e90b41f9e9a12b3d3a450 (https://github.com/nunit/nunit3-vs-adapter/pull/984).

I've not delved into the details of that commit, but it's clear that there is a problem that needs fixing.

### PR DESCRIPTION
**Pull request by Socolin**
Fixes #1124

### CODE REVIEW

**Comment by Socolin** [comment]
I was not able to run the tests on my computer, but they seems to work in github action.

**Comment by OsirisTerje** [comment]
@Socolin This is still open, build issues, merge conflicts.  Any chance of having a look?

**Comment by Socolin** [comment]
I'll take a look I did not saw the build error I was waiting for some feedback on this.

**Comment by OsirisTerje** [comment]
Your unit test is failing.  See [Details](https://github.com/nunit/nunit3-vs-adapter/actions/runs/7241472832/job/19725613979?pr=1147), nearly near the bottom.

**Comment by Socolin** [comment]
Hello, the test result is not available anymore could you trigger the pipeline again so I can see the errors ? I will have time again to look at this in the coming weeks.

**Comment by OsirisTerje** [comment]
I did  a manual merge from main (who had changed) on the web here, and got in some compiler errors.  I think it is faster if you just fix those than for me to clone your repo.  Then the build should work again.

**Comment by Socolin** [comment]
Sorry for the delay, I finally got the time to take a look, I rebased the branch + force push and did the fix, all should be good now :)

**Comment by OsirisTerje** [comment]
Lgtm, any comments @manfred-brands , @stevenaw ?

**Review by stevenaw — CHANGES_REQUESTED** [review]
This looks great thanks for your contribution @Socolin 

No concerns from what I can research about this, but I admit that console colors are not something I know much about. I'd appreciate another pair of eyes from a team member. Would it make sense to add a few more negative tests for cases with leading `[` but otherwise invalid formats after?

**Review by stevenaw — APPROVED** [review]
Actually, I'm going to go ahead and approve as I don't want to necessarily hold up merging over this, but I'd appreciate understanding if we thought it a case we'd want a test over

**Pull request merged**
