### PR TITLE
Add Linux CI job

### PR DESCRIPTION
**Pull request by jnm2**

### CODE REVIEW

**Comment by OsirisTerje** [comment]
@jnm2  Should this be merged ?   The builds seems to work now in master (and branches)

**Comment by jnm2** [comment]
There are two things I haven't been able to figure out yet before this could merge. How interested are you in Linux CI?

**Comment by OsirisTerje** [comment]
It would be "nice to have", but it is not critical.  Since we sometimes have issues on Linux, it would be nice to also see the acceptance tests running there.  I just had one such issue, but they are not very often. So if it currently is hard, don't spend all your effort there.  Then it can wait.

**Comment by ChrisMaddock** [comment]
Hey Joseph - FYI the Console tests have started failing in the same way.

Here's the backstory, looks like it should be fixed in Cake 0.37. Trying that out with the console now.

https://github.com/cake-build/cake/issues/2695

**Comment by jnm2** [comment]
This is an example of the result XML when our acceptance tests fail with `There should be a single test in the test results. Expected: 1 But was: 0`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<TestRun id="6ad82d92-a230-4204-a7a9-ff27bebb8998" name="@Ubuntu 2020-02-02 12:29:43" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2020-02-02T12:29:43.2862360-05:00" queuing="2020-02-02T12:29:43.2862361-05:00" start="2020-02-02T12:29:43.1929794-05:00" finish="2020-02-02T12:29:43.2908704-05:00" />
  <TestSettings name="default" id="d3e94493-90b4-4076-a7e5-97fbca0e0e6e">
    <Deployment runDeploymentRoot="_Ubuntu_2020-02-02_12_29_43" />
  </TestSettings>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="0" executed="0" passed="0" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="Ubuntu" outcome="Error" timestamp="2020-02-02T12:29:43.2670366-05:00">
        <Text>Testhost process exited with error: The specified deps.json [/home/joseph/Source/Repos/nunit3-vs-adapter/.acceptance/1/Single_target_csproj_dotnet_CLI(netcoreapp3.1)/bin/Debug/netcoreapp3.1/Test.deps.json] does not exist
. Please check the diagnostic logs for more information.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>
```

**Comment by jnm2** [comment]
Last outstanding question so far. Why is the engine happy on .NET Framework but unable to find Mono.Cecil on .NET Core?

> Dependent Assembly Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e of /home/vsts/work/1/s/.acceptance/1/Single_target_vbproj_dotnet_CLI(netcoreapp3.1)/bin/Debug/netcoreapp3.1/Test.dll not found. Can be ignored if not a NUnit project.
>
> No test is available in /home/vsts/work/1/s/.acceptance/1/Single_target_vbproj_dotnet_CLI(netcoreapp3.1)/bin/Debug/netcoreapp3.1/Test.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

```
    at NUnit.Engine.Services.DriverService.GetDriver(AppDomain domain, String assemblyPath, String targetFramework, Boolean skipNonTestAssemblies)
    at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
    at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
    at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
    at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
    at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Explore(TestFilter filter) in /home/vsts/work/1/s/src/NUnitTestAdapter/NUnitEngine/NUnitEngineAdapter.cs:line 81
    at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in /home/vsts/work/1/s/src/NUnitTestAdapter/NUnit3TestExecutor.cs:line 245
```

**Comment by ChrisMaddock** [comment]
May not be related, but this is the same error message as https://github.com/nunit/nunit-console/issues/710.

Are you running these tests from a different directory or something? Don't think I've seen this when running under the adapter before, as it normally sits in the same directory as the tests themselves, right?

**Comment by jnm2** [comment]
I verified that this line is returning null. I think it's a case-sensitivity issue when we build on Linux:

https://github.com/nunit/nunit3-vs-adapter/blob/e7253d7ba928d89477cba6e89dd5b41a9b1de474/src/NUnitTestAdapter/EmbeddedAssemblyResolution.cs#L91

**Comment by jnm2** [comment]
Not quite a case-sensitivity issue! A path separator issue:

image

https://github.com/nunit/nunit3-vs-adapter/blob/e7253d7ba928d89477cba6e89dd5b41a9b1de474/src/NUnitTestAdapter/NUnit.TestAdapter.csproj#L59-L60

**Comment by ChrisMaddock** [comment]
Good spot!

**Comment by jnm2** [comment]
I have to say, fighting with tooling and CI is a bit https://www.reddit.com/r/funny/comments/cjbnk9/where_did_all_my_money_go 😁

**Comment by jnm2** [comment]
@OsirisTerje Ready for review and merge now!

**Pull request merged**
