### PR TITLE
Fully qualified name change

### PR DESCRIPTION
**Pull request by OsirisTerje**
See issue #404

### CODE REVIEW

**Comment by CharliePoole** [comment]
@OsirisTerje Is this ready for review or do you need to make changes based on the discussion on #404?

**Comment by OsirisTerje** [comment]
Docs from Peter here:  https://github.com/Microsoft/vstest-docs/pull/95

**Comment by rprouse** [comment]
@OsirisTerje are you waiting for anything in this PR to merge and close?

**Comment by OsirisTerje** [comment]
Just need to resolve the conflicts and its good to go
...in progress.....

**Comment by CharliePoole** [comment]
@OsirisTerje This looks good to me based on what we have been told by Microsoft - that the presence of arguments is not required and that FQNs don't have to be unique. 

Have you verified that in the IDE? Does it work now, or does it depend on changes they are making?

**Comment by OsirisTerje** [comment]
This is unfortunately not working as it should, or as hoped.  We loose information and what is displayed in the test explorer are less than before.  
image

(1) This is the former way it was displayed, one test per specific set of test cases.  
(2) With this change it now displays like this, it looks like only one of the tests is displayed, but this just because the mismatch between the display name and the FQN.  
(3) Running the tests displays the 3 different test cases.

Having the results like 2-3 is one the biggest complaints we get.  Using the special FQN names they display better.  

What is needed here is a change in the Test Explorer and an explicit support for test cases (aka data driven tests).  
The discovery must list all variations in the test explorer.  One way it could be done is to add one more hierarchical level. That would have made more sense. 

@peterwald  I suggest we delay this change so that we don't annoy people with reduced functionality, and redo this when the test explorer can handle test cases properly.

**Comment by peterwald** [comment]
@OsirisTerje I agree with holding this change. The issue here is that if FQN is not unique, then the ID must be made unique. 

Either we need to include the parameters in the FQN in order to make it unique, or you need to assign the `TestCase.Id` before returning it. If the Id is not assigned, then it is constructed from a hash of the Source,Executor, & FQN. The Source and Executor are not changing, so the FQN would determine the uniqueness of the test case.

We are already normalizing the FQN currently, so the existing strategy should continue to work until we have a chance to address the data-driven tests.

**Pull request closed without merging**
