### PR TITLE
Upgrade to NUnit 3.4.1

### PR DESCRIPTION
**Pull request by CharliePoole**
This fixes issue #180

### CODE REVIEW

**Comment by bbi-yggy** [comment]
We recently upgraded to the 3.4.1 version of NUnit and the Visual Studio 2015 test adapter, and now we are periodically getting test discovery failures with an error about not being able to load the Mono.Cecil.Rocks assembly. Has anyone else seen this? I will try to track down more details on the repro steps, as it has been frustratingly inconsistent.

**Comment by CharliePoole** [comment]
Would that be the NUnit 3 VS Adapter 3.4? That was the last release of the adapter. It uses the NUnit 3.4.1 engine. In terms of repro, it could make a difference whether you use the vsix or the nuget package.

**Comment by bbi-yggy** [comment]
Yup, we're using the NUnit 3 Test Adapter 3.4.0. I _think_ I installed from the vsix package, but I remember messing around with it for a while and that may not be correct. Don't spend any time on our issue until I can get you solid info, mostly I wondered if there was a known problem along the lines of what we're seeing.

**Comment by mariuszjamro** [comment]
I'm having the same problem when using adapter 3.4.0.0 and nunit 3.2.1 on .net 3.5. Adapter is complaining about not found Mono.Cecil.Rocks.

I noticed that it works correctly when project has target framework version set to .net 4.5.

**Comment by rprouse** [comment]
@bbi-yggy and @mariuszjamro I entered issue #205 to track the issues you are seeing.

**Pull request merged**
