### PR TITLE
Support .NET Core

### LINKED ISSUE #297: Support for .Net Core projects
@galvesribeiro commented on [Sat Jan 14 2017](https://github.com/nunit/nunit/issues/1981)

Visual Studio is throwing this:

```
------ Discover test started ------
NUnit Adapter 3.6.0.0: Test discovery starting
Error: Unable to get runner for this assembly. Check installation, including any extensions.
FileNotFoundException: Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified.
Dependent Assembly nunit.framework of C:\Users\gutem\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1\bin\Debug\netstandard1.6\ClassLibrary1.dll not found. Can be ignored if not a NUnit project.
NUnit Adapter 3.6.0.0: Test discovery complete
========== Discover test finished: 0 found (0:00:00.655) ==========
```

This is the sample .csproj:

```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170113-02" />
    <PackageReference Include="NETStandard.Library" Version="1.6.1" />
    <PackageReference Include="NUnit" Version="3.6.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.6.0" />
  </ItemGroup>
</Project>
```
With this sample test:

```
[TestFixture]
    public class Class1
    {
        string teststring = "";

        [SetUp]
        public void SetUp()
        {
            teststring = "AAA";
        }

        [Test]
        public void TestDemo()
        {
            Assert.True(teststring.Equals("AAA"));
        }
    }
```

Do we need to do anything else?

Thank you.

---

@jnm2 commented on [Sat Jan 14 2017](https://github.com/nunit/nunit/issues/1981#issuecomment-272651346)

@CharliePoole I wonder if this is https://github.com/nunit/nunit3-vs-adapter/issues/296?

@galvesribeiro Can you see if the NUnit console runner runs the tests properly?

---

@galvesribeiro commented on [Sat Jan 14 2017](https://github.com/nunit/nunit/issues/1981#issuecomment-272651605)

@jnm2 what should I do to use the console runner on .net standard projects?

---

@JustinRChou commented on [Sat Jan 14 2017](https://github.com/nunit/nunit/issues/1981#issuecomment-272651617)

Seems like it.
NUnit Adapter 3.6.1.0 has the same issue.

---

@jnm2 commented on [Sat Jan 14 2017](https://github.com/nunit/nunit/issues/1981#issuecomment-272652926)

@galvesribeiro Download the zip from https://github.com/nunit/nunit-console/releases and run `nunit3-console "path\to\test\assembly.dll"` at the command line.

---

@jnm2 commented on [Sat Jan 14 2017](https://github.com/nunit/nunit/issues/1981#issuecomment-272653087)

@JustinRChou can we make these new-style .csproj's part of the VS adapter tests, both .NET Standard and .NET Framework? A single project can multitarget and produce both binaries.

### PR DESCRIPTION
**Pull request by rprouse**
**Do Not Merge**

Fixes #297 

Starting a PR so that people can easily find the most recent AppVeyor NuGet feed builds for testing. This produces a NuGet package. It currently does not produce a VSIX. I have also up'd the version to 4.0 because these are major changes. It isn't inline with our original plans for 4.0 which included running NUnit 2.x tests, so feel free to object to the version.

These changes **require** that the new `dotnet` CLI and the .NET SDK to be installed and only builds in Visual Studio 2017.

Work still to do,

- [x] Re-add .NET 3.5 support
- [x] Get the AppVeyor build working
- [x] Re-add the VSIX project and figure out how to multi-target it
- [x] Figure out why `dotnet test` is not working
- [x] Enable the VSTest tests in `build.cake`
- [x] Add .NET Core projects to the demo projects
- [x] Full CLR tests are no longer being discovered

### CODE REVIEW

**Comment by CharliePoole** [comment]
My concern would be running tests targeting 2.0, 3.5, 4.0 under those runtimes. Current adapter does that. It looks like this will not be available, although I may be wrong. Unfortunately, it's not something the unit tests tell us.

**Comment by rprouse** [comment]
Well, that was a lot of checkins getting this building and producing a NuGet package artifact, but this is now one step closer to being ready. I have added a list of remaining tasks that need to be dealt with before this PR is merged. The one I could use the most help with is figuring out why the `dotnet test` command isn't working.

**Comment by rprouse** [comment]
`dotnet test` is now working at the command line and I've been able to run .NET Core and full .NET tests from VSTest, in Visual Studio and using `dotnet test`. Some additional work to do then we should be able to review this in earnest.

**Comment by rprouse** [comment]
Finally, everything is building and passing again. @OsirisTerje do you have time to review this?

**Comment by rprouse** [comment]
To prove that this is working, I have setup NUnit tests targeting various platforms like .NET Core and full .NET referencing the CI builds of this PR and the corresponding PR for the engine. There are a mix of projects using the full framework, .NET Core, and, the new and old CSPROJ formats. It can be clones from https://github.com/rprouse/NUnitPlatformTests.

### Projects

- **src\NetStandard13Library** - A .NET Standard 1.3 project to be referenced by a test project.
- **src\NetStandard16Library** - A .NET Standard 1.6 project to be referenced by a test project. Contains async methods for testing.
- **test\NetCore10Tests** - A .NET Core 1.0 test project referencing the .NET Standard 1.3 Library.
- **test\NetCore11Tests** - A .NET Core 1.1 test project referencing the .NET Standard 1.6 Library.
- **test\NetClrNewStyleTests** - A .NET 4.5.2 test project using the new CSPROJ format.
- **test\NetClrTests** - A .NET 4.5 test project using the old CSPROJ format.

### Dependencies

Any tests using the new style CSPROJ format, either .NET Core or .NET 4.x, need to add a `PackageReference` to the NuGet package `Microsoft.NET.Test.Sdk`.

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
  <PackageReference Include="NUnit" Version="3.6.1" />
  <PackageReference Include="NUnit3TestAdapter" Version="4.0.0-ci-00452-pr-313" />
</ItemGroup>
```

### Running Tests
#### Visual Studio

I have tested going to source for all projects and tests, it works fine.

image

#### dotnet test

.NET Core test can be run on the command line with `dotnet test`, for example,

```cmd
> dotnet test .\test\NetCore10Tests\NetCore10Tests.csproj
Build started, please wait...
Build completed.

Test run for D:\src\NUnit\NUnitPlatformTests\test\NetCore10Tests\bin\Debug\netcoreapp1.0\NetCore10Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 4.0.0.0: Test execution started
Running all tests in D:\src\NUnit\NUnitPlatformTests\test\NetCore10Tests\bin\Debug\netcoreapp1.0\NetCore10Tests.dll
NUnit3TestExecutor converted 14 of 14 NUnit test cases
NUnit Adapter 4.0.0.0: Test execution complete

Total tests: 14. Passed: 14. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 5.4507 Seconds
```

#### vstest.console.exe

The .NET 4.5 tests can also be run with `vstest.console.exe`. The .NET Core tests are not running because they are not finding the dependent assemblies (`nunit.framework.dll`) which are not copied into the bin directory on build. I am not sure if this is expected behaviour. I would think most people would use `dotnet test`, but it needs looking into.

```cmd
> vstest.console.exe .\test\NUnitClrTests\bin\Debug\NUnitClrTests.dll /TestAdapterPath:packages
Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Information: NUnit Adapter 4.0.0.0: Test execution started

Information: Running all tests in D:\src\NUnit\NUnitPlatformTests\.\test\NUnitClrTests\bin\Debug\NUnitClrTests.dll

Information: NUnit3TestExecutor converted 1 of 1 NUnit test cases

Information: NUnit Adapter 4.0.0.0: Test execution complete

Passed   TestMethod

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 0.4058 Seconds
```

**Comment by OsirisTerje** [comment]
@rprouse  Yes, Rob, I'll pull it down and will walk through it.

**Comment by roederja2** [comment]
Could you publish your nuget package so we can test it?

**Comment by rprouse** [comment]
@roederja2 the NuGet packages are published to our AppVeyor feeds, so you can test with those. You will need to add the Engine and Adapter feeds to a `NuGet.config` file like this, https://github.com/rprouse/NUnitPlatformTests/blob/master/NuGet.Config

You can then use `PackageReferences` like the one in my comment above. Also, see https://github.com/rprouse/NUnitPlatformTests for example project if you need help.

Once this PR and the Engine PR is reviewed, I will release an `alpha1` release of the two required packages for people to test with without modifying their NuGet.config files. We need to go through our code review, approval and release process first though.

**Comment by bernardbr** [comment]
Hello @rprouse do you know if this (https://github.com/OmniSharp/omnisharp-vscode/issues/1434) needs your attention?

Thanks!

**Comment by rprouse** [comment]
@bernardbr thanks for linking me in on that issue. I didn't realize VSCode used the adapter in that way, so I will put it on my radar 👍

**Comment by MihaMarkic** [comment]
Tested it briefly and indeed, it works. Huraa. Doesn't work with CodeRush for Roslyn at this time though. I'll let them know.

**Comment by roederja2** [comment]
It doesn't work for me :( : 
```
Starting test execution, please wait...
NUnit Adapter 4.0.0.0: Test execution started
Running all tests in <MyDLL>.dll
Exception System.TypeLoadException, Exception thrown executing tests in <MyDLL>.dll
Could not find symbol provider type Mono.Cecil.Pdb.NativePdbReaderProvider
NUnit Adapter 4.0.0.0: Test execution complete
No test is available in <MyDLL>.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```

This may be because my target framework is netcoreapp1.1 - it needs to be because the dll I'm testing is also targeting netcoreapp1.1 - my tests are in a different dll than the code under test. I'm running this under windows.

```
  <ItemGroup>
    <ProjectReference Include="..\<MyProject>.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0-ci-00452-pr-313" />
  </ItemGroup>
```

Where am I supposed to use the engine package that you mentioned?

**Comment by MihaMarkic** [comment]
@roederja2 It works just fine for me (.NETCoreApp1.1). Did you add proper NuGet.Config?

**Comment by roederja2** [comment]
Yes, the package installed fine. I wonder why it would reference a Mono dll though.

**Comment by rprouse** [comment]
@roederja2 there is a .NET Core App 1.1 project in my test solution and that is working. It is referencing a .NET Standard 1.6 assembly that is being tested. You are referencing another .NET Core App, but I don't know why that would be different.

You don't need to add a dependency for the NUnit.Engine, it is already a dependency of the adapter. Mono.Cecil is included with the engine and is used to read the test assemblies and PDB files to speed up reflection and provide source code line numbers to Visual Studio for navigation. It isn't Mono, just a NuGet package from the Mono project that is pulled in by NUnit.

I will see if I can reproduce your issue in my test project. Do you have a simple repro that you can ZIP up and share to save me time? I have an idea what the problem is and will take a look, but would like to see it fail and then see it start working when I fix it. TDD 😄

**Comment by bernardbr** [comment]
@rprouse 
don't mention it!

**Comment by rprouse** [comment]
@roederja2 I added a `netcoreapp1.1` test project that references a `netcoreapp1.1` project to my demo project at https://github.com/rprouse/NUnitPlatformTests and it works fine for me.

The project file for the app under test looks like this,

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

</Project>
```

And the test project looks like this,

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0-ci-00452-pr-313" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NetCoreApp11\NetCoreApp11.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
```

Can you look at your projects and try to identify the differences or provide a repro that I can test with?

**Comment by roederja2** [comment]
@rprouse : It seems like it was a corrupted package cache or something. After I deleted the bin and obj directory and ran dotnet restore again it started working.

**Comment by necoras** [comment]
@rprouse : I pulled down version v4.0.0-dev-00386 of the test adapter and v3.7.0-dev-03862 of the NUnit packages from the AppVeyor and MyGet feeds respectively in hopes of solving [this issue](https://github.com/nunit/docs/issues/180). I'm still seeing this error when building my project. Was this issue expected to be fixed in the latest builds?

**Comment by roederja2** [comment]
@necoras You need to use version 4.0.0-ci-00452-pr-313

**Comment by necoras** [comment]
@roederja2 That did the trick. Thanks!

**Comment by rprouse** [comment]
@necoras that is an unfortunate side-effect of our naming scheme. This is still a PR, so any master builds appear "newer" in NuGet because `dev` comes after `ci`. The `dev` builds will start working once we merge  😉

**Comment by rprouse** [comment]
I pushed a setting to fix OmniSharp/omnisharp-vscode#1434. The problem was that the `IRunSettings` passed in with the `IDiscoveryContext` can be null, in fact, the documentation at https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0007-Editors-API-Specification.md#start-discovery-request has an example with the `RunSettings` being set to null. We've never had to deal with this because Visual Studio always set it, but now that there are more IDE's and runners using this adapter, we should implement the correct fix.

**Comment by brantburnett** [comment]
@rprouse 

In your list of test projects above using different frameworks, I didn't see anything mentioning multi-targeting.  I think that an NUnit test project that targets multi frameworks should probably be supported.  If I'm writing a library that uses multi-targeting, I'd like the tests to run against each target as well.

In my initial testing, it does appear to work when run with "dotnet test".  I just took a NUnit test project and changed from `<TargetFramework>netcoreapp1.0</TargetFramework>` to `<TargetFrameworks>netcoreapp1.0;net46</TargetFrameworks>`.

It's not working in VS, but I'm pretty sure VS is known to not support multi-targeting tests.  So not much you can do about that.

Anyway, I just thought you might want to add this use case to your set of tests.

Thanks,
Brant

**Comment by DustinCampbell** [comment]
@brantburnett: In my experience, reordering the target frameworks so that `net46` is first will allow them to run in VS.

**Comment by bernardbr** [comment]
@brantburnett I use this when I need create an interpolable class library, for example, that will be run in both frameworks (NetCore and NetFramework).

But in my opinion, when do you need test differents frameworks the best practice is create 2 projects with different target framework and run tests from there...

**Comment by rprouse** [comment]
@OsirisTerje has finished his code review via email. Thank you @OsirisTerje.

Based on our conversations, we decided to revert back to version `3.8.0-alpha1`. We both thought it would be confusing to have an NUnit 3 adapter with version 4.0, so decided to stick with our original plan of reserving 4.0 for when we merge the two adapter projects. There are also no major changes to the full .NET version of the adapter and it is not a breaking change, so according to semver, we probably shouldn't increment the major number yet.

**If anyone else would like to review this, please do so today.** I plan on merging this evening and doing an alpha release to NuGet. Before that, I am going to pull the recent changes and give them one last test and start writing some documentation on how to use this in .NET Core projects.

**Comment by bernardbr** [comment]
Thank you very much @rprouse !

**Comment by bernardbr** [comment]
Thank you very much @rprouse !

**Comment by CurlyFire** [comment]
Thank you all for adding this feature!

**Comment by MikeBeaton** [comment]
Hi, This is brilliant, many thanks!

I've just successfully run a set of tests on a project which dual targets netcoreapp1.1 and net45. It runs all the tests fine (256 tests on net45, 153 on netcoreapp1.1), and from a very quick look it supports debugging the selected tests etc. just as before too.

I did note that if I am using multi-targetting with, e.g.  `<TargetFrameworks>net45;netcoreapp1.1</TargetFrameworks>` then the Visual Studio test explorer only seems to show and run the tests as for the first listed target?

I am on Visual Studio Professional 2017 15.0.0.0+26228.9

Also, I was previously building and targeting this project against net40 upwards, but it looks as if the dependency on Microsoft.NET.Test.Sdk v15.0.0 means that the lowest .NET Framework version I can test this way is net45, because if I try to target net40 I get:

````
Package Microsoft.TestPlatform.TestHost 15.0.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package Microsoft.TestPlatform.TestHost 15.0.0 supports:
  - net45 (.NETFramework,Version=v4.5)
  - netstandard1.5 (.NETStandard,Version=v1.5)
````

**Comment by rprouse** [comment]
@MikeBeaton that does seem to be an unfortunate limitation of multi-targeting with the new CSPROJ format. AFAIK, `Microsoft.NET.Test.Sdk` is required to run tests against the new project format. Our adapter does work with older frameworks, but only using the old CSPROJ format.

image

**Comment by rprouse** [comment]
For anyone who wants to start working with the new test adapter, I have written a blog post covering it's usage. Once everything settles down, I will migrate the core info into the docs, but for now, instructions are at http://www.alteridem.net/2016/10/03/nunit-unit-tests/

**Comment by MikeBeaton** [comment]
Found another slight quirk (I saw this last night, but thought it might help if I replicate it and report on it this morning).

If I have the 3.7 VSIX and the 3.8-alpha NuGet package both installed (I do realise this is a non-supported configuration, although I suppose it's quite easy to get there by mistake...!) then, when I test a netcoreapp1.1 target, it uses the 3.8 test engine (
````
------ Discover test started ------
NUnit Adapter 3.8.0.0: Test discovery starting
NUnit Adapter 3.8.0.0: Test discovery complete
========== Discover test finished: 137 found (0:00:01.1684465) ==========
------ Run test started ------
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in C:\Projects\...\net.core.shared\tests\bin\Debug\netcoreapp1.1\...Tests.dll
NUnit3TestExecutor converted 137 of 137 NUnit test cases
NUnit Adapter 3.8.0.0: Test execution complete
========== Run test finished: 137 run (0:00:14.4474454) ==========
````
), but if I test a net45 target, it uses the 3.7 test engine (
````
------ Run test started ------
NUnit Adapter 3.7.0.0: Test execution started
Running all tests in C:\Projects\...\net.core.shared\tests\bin\Debug\net45\...Tests.dll
NUnit3TestExecutor converted 256 of 256 NUnit test cases
NUnit Adapter 3.7.0.0: Test execution complete
========== Run test finished: 256 run (0:00:23.7608298) ==========
````
).

These are each from exactly the same multi-targetted solution, using new format .csproj files throughout, so I'm not qute sure what's going on!

**Comment by MikeBeaton** [comment]
@rprouse I feel a bit stupid posting this, but I think after all the hard (and very much appreciated!) work, you posted the wrong link above (?!), should have been http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/ ? :)

**Comment by rprouse** [comment]
@MikeBeaton thanks for pointing out the bad link. I've fixed it in my comment.

**Comment by MikeBeaton** [comment]
(Hi. I was still trying to understand what happened as reported in my comment 3 above this. I think if I'm understanding it correctly, then it is that NUnit 3.7 *can* support new .csproj files, as long as Microsoft.NET.Test.Sdk 15.0.0 is installed, but not for .NET Core? Sorry - I know this is not a bug or an issue as such!)

**Comment by rprouse** [comment]
@MikeBeaton when Visual Studio attempts to find tests in a project, it asks each installed VSIX and NuGet adapter in turn if they can run the tests and I believe it stops asking when it finds an adapter that works.

So, it looks like VS asks the VSIX first. For .NET Core tests, the 3.7 VSIX will not run the tests, so it moves on until the 3.8 NuGet package runs them. For .NET 4.5, the 3.7 VSIX can run them so it does and the 3.8 never gets a chance.

Unfortunately, VS doesn't see a NuGet adapter as newer than the installed VSIX. To VS, they are different things.

**Comment by OsirisTerje** [comment]
I can confirm this, wrote about it back in 2013,  https://blogs.msdn.microsoft.com/visualstudioalm/2013/06/11/part-3-unit-testing-with-traits-and-code-coverage-in-visual-studio-2012-using-the-tfs-build-and-the-new-nuget-adapter-approach/  saying 

_"One thing to be aware of is that the VSIX adapter takes precedence over the NuGet adapter, if you have both installed.  Even if you update the NuGet adapter to a later version than the VSIX, the VSIX will be used.   That means you might run on an earlier version of the adapter, whereas TFS Build and developers who don’t have the VSIX will use the newer NuGet version. "_

Neither MSTest2 nor XUnit delivers their adapters as VSIX, and my guess (un-informed and unconfirmed)  is VSIX test adapters are not going to get much support from MS moving forward.   The recommended approach should be to add the nuget adapters to all solutions and uninstall the vsix from all devs machines.

**Comment by MikeBeaton** [comment]
Dear both, Many thanks for confirmation of this. For me, it wasn't so much that the VSIX gets precedence, I can see from an engineering point of view why VS might not be expected to know that that the VSIX and NuGet versions are the same thing, but rather I wasn't expecting to see 3.7 running tests from new format .csproj files at all! :)

**Comment by rprouse** [comment]
@MikeBeaton other than the way that we package it, the full .NET version of the adapter in the alpha is the same as the 3.7 adapter, so it isn't too surprising that it works.

**Comment by MikeBeaton** [comment]
Yes! It was more the parsing of the csproj file that I was surprised by, not the executing of the tests in .NET Framework - I think I'd got confused and thought that the issue being addressed by the update was support for the new csproj format as well as support for Core, but obviously not. :) Thanks again for all this work.

**Pull request merged**
