### PR TITLE
- NewFileForEachRun setting: always create new xml file

### PR DESCRIPTION
**Pull request by netcorefactory**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nunit/nunit3-vs-adapter?pullRequest=799) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nunit/nunit3-vs-adapter?pullRequest=799) before we can accept your contribution.<br/><br/>:x: netcorefactory [sign now](https://cla.dotnetfoundation.org/nunit/nunit3-vs-adapter?pullRequest=799)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nunit/nunit3-vs-adapter?pullRequest=799) it.</sub>

**Comment by OsirisTerje** [comment]
Thanks for the PR.  

Can you raise a separate issue to cover this, please ?  And link to that.

A bit unsure if the NewFileForEachRun is clear enough, since the adapter can produce other files.  Perhaps add OutputXml to it ?   Like NewOutputXmlFileForEachRun ?

**Comment by netcorefactory** [comment]
https://github.com/nunit/nunit3-vs-adapter/pull/799#issuecomment-724661532

**Review by OsirisTerje — CHANGES_REQUESTED** [review]

**Comment by OsirisTerje** [comment]
@netcorefactory Did you see the comment on the property name?

**Comment by netcorefactory** [comment]
@OsirisTerje any estimate this change will be available? Thanx

**Review by OsirisTerje — APPROVED** [review]

**Comment by OsirisTerje** [comment]
It is in beta.1 of the 4.0.0, which is due any day now....  just need to finish up the release notes and go through.  Hope to be able to have this done during this week.

**Comment by netcorefactory** [comment]
@OsirisTerje  Great news,  Thanks a lot!

**Pull request merged**
